# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 07:15
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160425_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publication_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 4, 25, 7, 15, 24, 58880, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
    ]
