# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 07:24
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160425_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 4, 25, 15, 24, 26, 896637)),
        ),
    ]
