# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20160522_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.IntegerField(max_length=11),
        ),
    ]
