# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20160522_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colume1', models.CharField(max_length=10)),
                ('colume2', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['colume1'],
            },
        ),
    ]
