# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 03:03
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_ctest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctest',
            name='colume3',
            field=models.CharField(default=datetime.datetime(2016, 6, 30, 3, 3, 11, 212404, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
