# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20160705_1436'),
        ('books', '0015_ctest_colume3'),
    ]

    operations = [
    ]
